# Generated by Django 5.1.2 on 2024-10-25 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'We already have a recipe with the same title!'}, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('cuisine_type', models.CharField(choices=[('FR', 'French'), ('CN', 'Chinese'), ('IT', 'Italian'), ('BK', 'Balkan'), ('OT', 'Other')], max_length=7)),
                ('ingredients', models.TextField(help_text='Provide the cooking time in minutes.')),
                ('cooking_time', models.PositiveIntegerField(help_text='Provide the cooking time in minutes.', validators=[django.core.validators.MinValueValidator(1)])),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
